version: "3.9"

services:
  simpleweb:
    image: python:3.11.3-alpine3.16 # using alpine because the image is smaller and quick to load
    build: .
    ports:
      - 80:80
    volumes:
      - ./simplewebsite:/www
    working_dir: /www
    # -u sends the logs unbuffered so they print out straight away
    # uncomment the below entrypoint: line to bypass the entrypoint script and just host the web files
    # entrypoint: "python3 -u -m http.server" # SimpleHTTPServer is for python 2
