version: "3.9"

services:
  python:
    image: python:3.11.3-alpine3.16 # using alpine because the image is smaller and quick to load
    ports:
      - 8000:8000
    volumes:
      - ./simplewebsite:/www
    working_dir: /www
    entrypoint: "python3 -m http.server" # SimpleHTTPServer is for python 2
