name: Pulumi
on:
  push:
    branches:
      - main
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v3
      - name: Run Pulumi
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: jamest/sre-challenge/dev # When using an individual account, only use stack-name. <-- this advice from pulumi is wrong, and results in error: If you're using the --stack flag, pass the fully qualified name (org/project/stack)
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
